### ISSUE TITLE
C++ module support

### ISSUE THREAD

**Issue by Stef-2** [Cvelth/vkfw#3]
Not really an issue, but seeing as https://github.com/KhronosGroup/Vulkan-Hpp now exports their headers as modules, I'm wondering if you considered doing something similar, mainly to cut down on compile times.

Regardless, thank you for your work, this project has been very useful.

Cheers.

**Comment by Cvelth** [comment]
Hi. Thanks for the feedback.

Sadly currently only msvc compiler supports modules in a non-experimental fashion. And I don't have resources and/or time for supporting/testing multiple compiler-independent versions of the project. I'll keep it in mind though. It might be worth a switch once C++20 support is more complete all around the board.

Also if anything, feel free to make a pull request if there's anything you want to be merged in. I don't think a PR that introduces something unsupported by multiple major compilers would be merged in any soon, but it would probably be eventually.
