### ISSUE TITLE
Will support for GLFW 3.4 be added?

### ISSUE THREAD

**Issue by Volatus** [Cvelth/vkfw#5]
Currently VKFW will report that `glfw` version 3.4 is not supported.

**Comment by Cvelth** [comment]
I just pushed experimental support for 3.4. I didn't have time to extensively test it, so if you run into any issues, please let me know.

**Comment by Volatus** [comment]
Got it, will test.

**Comment by Volatus** [comment]
@Cvelth Small syntax problem here: https://github.com/Cvelth/vkfw/blob/582359f4792bac66736729dddad4907fa863dccf/include/vkfw/vkfw.hpp#L2385-L2387

**Comment by Cvelth** [comment]
Done, thanks.
